title: Engineering Systems Optimization
author: Tom van Woudenberg
email: T.R.vanWoudenberg@tudelft.nl 
logo: pages/figures/logo.jpg
only_build_toc_files : True

execute:
  execute_notebooks: 'off'

html:
  favicon : "pages/figures/favicon.ico"

sphinx:
  config:
    bibtex_reference_style: author_year
    html_show_copyright: false
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]      
    html_theme_options:
      repository_url: "https://gitlab.tudelft.nl/interactivetextbooks-citg/engineering-systems-optimization"
      baseurl : "https://teachbooks.tudelft.nl/engineering-systems-optimization/"
      use_repository_button: true
      use_issues_button : true
      launch_buttons:
          thebe: true
  extra_extensions:
  - download_link_replacer

bibtex_bibfiles:
  - references.bib
