title: Engineering Systems Optimization
author: Tom van Woudenberg
email: T.R.vanWoudenberg@tudelft.nl 
logo: pages/figures/logo.jpg

execute:
  execute_notebooks: 'off'

launch_buttons:
  thebe: true

sphinx:
  config:
    bibtex_reference_style: author_year
    html_show_copyright: false
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]      
  extra_extensions:
  - sphinx_inline_tabs
  - sphinx.ext.imgconverter
  - download_link_replacer

bibtex_bibfiles:
  - references.bib

html:
  extra_footer: <img src="https://i.creativecommons.org/l/by/4.0/88x31.png" width="88px">
