title: Engineering Systems Optimization
author: Tom van Woudenberg and Maria Nogal, built with <a href="https://teachbooks.tudelft.nl/">TeachBooks</a> and <a href="https://jupyterbook.org/">Jupyter Book</a>, <a href="https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer"">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt="">
email: T.R.vanWoudenberg@tudelft.nl 
logo: pages/figures/logo.jpg
only_build_toc_files : True
copyright: Delft University of Technology, CC BY 4.0

execute:
  execute_notebooks: 'off'

html:
  favicon : "pages/figures/favicon.ico"
  baseurl :  "https://teachbooks.tudelft.nl/engineering-systems-optimization/"
  home_page_in_navbar       : true

sphinx:
  config:
    bibtex_reference_style: author_year
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]      
    html_theme_options:
      repository_url: "https://github.com/TeachBooks/engineering-systems-optimization"
      use_repository_button: true
      use_issues_button : true
      launch_buttons:
          thebe: true
      html_show_copyright: false
  extra_extensions:
  - download_link_replacer

bibtex_bibfiles:
  - references.bib
